name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '8.1' ]
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

  coding-standard:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '8.1' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install

      - name: PHPCS
        run: |
          cp ./phpcs.xml.dist ./phpcs.xml
          ./vendor/bin/phpcs --config-set php_version 801010 --exclude=Generic.Files.LineLength

      - name: PHPSTAN
        run: |
          cp ./phpstan.neon.dist ./phpstan.neon
          php -d memory_limit=-1 ./vendor/bin/phpstan analyse ./src phpstan.neon

      - name: DEPTRAC
        run: php -d memory_limit=-1 ./vendor/bin/deptrac analyse

  tests:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '8.1' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Configuration
        run: cp phpunit.xml.dist phpunit.xml
      - name: PHPUNIT
        run: vendor/bin/phpunit